services:
  config-server:
    ports:
      - "8071:8071"
  menu-service:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8080"
  order-service:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8080"
  customer-service:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8083:8080"
