services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizzadb
  config-server:
    build:
      context: ./config-server
      args:
        JAR_FILE: target/config-server-0.0.1-SNAPSHOT.jar
    image: amolina/config-server:latest
    ports:
      - "8071:8071"
  # menu-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   ports:
  #     - "8081:8080"
  # order-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   ports:
  #     - "8082:8080"
  # customer-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   ports:
  #     - "8083:8080"
